package com.bookishjava.models.database;

import jakarta.persistence.*;

import java.util.Date;

@Entity
public class Book {
    // Spring methodology for Primary Keys:
    // @Id Tells Spring this is the primary key.
    // @GeneratedValue, similar to SQL this explains to Spring this field is automatically generated.
    // If your database creation means Primary Keys are entered manually, instead of being generated by SQL, then we wont need this
    private @Id @GeneratedValue(strategy = GenerationType.IDENTITY) Long id;
    private String title;
    private String isbn;
    @Column(name = "published_date")    // Just confirming the column name, however Spring could have worked this out itself...
    private Date publishedDate;         // ... with its magic as the variable name matches.
                                        // This magic matching and guesswork also goes for Entity names matching table names FYI.



    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public Date getPublishedDate() {
        return publishedDate;
    }

    public void setPublished_date(Date publishedDate) {
        this.publishedDate = publishedDate;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((title == null) ? 0 : title.hashCode());
        return result;
    }
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Book other = (Book) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (title == null) {
            if (other.title != null)
                return false;
        } else if (!title.equals(other.title))
            return false;
        return true;
    }
}
